name: "Run ExUnit"

on:
  push:
    branches:
      - main
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '23'
          elixir-version: '1.11.2'
      - run: mix deps.get
      - run: mix test